services:
  app:                  # tu FastAPI + MQTT listener
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_app
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    restart: unless-stopped
