services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_app
    env_file:
      - .env
    depends_on:
    ports:
      - "${API_PORT}:${API_PORT}"
    restart: unless-stopped
